package model;
// Generated 21/09/2019 16:14:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private int id;
     private String name;
     private String countrycode;
     private String district;
     private int population;
     private Set countries = new HashSet(0);

    public City() {
    }

	
    public City(int id, String name, String countrycode, String district, int population) {
        this.id = id;
        this.name = name;
        this.countrycode = countrycode;
        this.district = district;
        this.population = population;
    }
    public City(int id, String name, String countrycode, String district, int population, Set countries) {
       this.id = id;
       this.name = name;
       this.countrycode = countrycode;
       this.district = district;
       this.population = population;
       this.countries = countries;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public int getPopulation() {
        return this.population;
    }
    
    public void setPopulation(int population) {
        this.population = population;
    }
    public Set getCountries() {
        return this.countries;
    }
    
    public void setCountries(Set countries) {
        this.countries = countries;
    }




}


