package model;
// Generated 21/09/2019 16:14:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private String code;
     private City city;
     private String name;
     private String continent;
     private String region;
     private float surfacearea;
     private Short indepyear;
     private int population;
     private Float lifeexpectancy;
     private BigDecimal gnp;
     private BigDecimal gnpold;
     private String localname;
     private String governmentform;
     private String headofstate;
     private String code2;
     private Set countrylanguages = new HashSet(0);

    public Country() {
    }

	
    public Country(String code, String name, String continent, String region, float surfacearea, int population, String localname, String governmentform, String code2) {
        this.code = code;
        this.name = name;
        this.continent = continent;
        this.region = region;
        this.surfacearea = surfacearea;
        this.population = population;
        this.localname = localname;
        this.governmentform = governmentform;
        this.code2 = code2;
    }
    public Country(String code, City city, String name, String continent, String region, float surfacearea, Short indepyear, int population, Float lifeexpectancy, BigDecimal gnp, BigDecimal gnpold, String localname, String governmentform, String headofstate, String code2, Set countrylanguages) {
       this.code = code;
       this.city = city;
       this.name = name;
       this.continent = continent;
       this.region = region;
       this.surfacearea = surfacearea;
       this.indepyear = indepyear;
       this.population = population;
       this.lifeexpectancy = lifeexpectancy;
       this.gnp = gnp;
       this.gnpold = gnpold;
       this.localname = localname;
       this.governmentform = governmentform;
       this.headofstate = headofstate;
       this.code2 = code2;
       this.countrylanguages = countrylanguages;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContinent() {
        return this.continent;
    }
    
    public void setContinent(String continent) {
        this.continent = continent;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public float getSurfacearea() {
        return this.surfacearea;
    }
    
    public void setSurfacearea(float surfacearea) {
        this.surfacearea = surfacearea;
    }
    public Short getIndepyear() {
        return this.indepyear;
    }
    
    public void setIndepyear(Short indepyear) {
        this.indepyear = indepyear;
    }
    public int getPopulation() {
        return this.population;
    }
    
    public void setPopulation(int population) {
        this.population = population;
    }
    public Float getLifeexpectancy() {
        return this.lifeexpectancy;
    }
    
    public void setLifeexpectancy(Float lifeexpectancy) {
        this.lifeexpectancy = lifeexpectancy;
    }
    public BigDecimal getGnp() {
        return this.gnp;
    }
    
    public void setGnp(BigDecimal gnp) {
        this.gnp = gnp;
    }
    public BigDecimal getGnpold() {
        return this.gnpold;
    }
    
    public void setGnpold(BigDecimal gnpold) {
        this.gnpold = gnpold;
    }
    public String getLocalname() {
        return this.localname;
    }
    
    public void setLocalname(String localname) {
        this.localname = localname;
    }
    public String getGovernmentform() {
        return this.governmentform;
    }
    
    public void setGovernmentform(String governmentform) {
        this.governmentform = governmentform;
    }
    public String getHeadofstate() {
        return this.headofstate;
    }
    
    public void setHeadofstate(String headofstate) {
        this.headofstate = headofstate;
    }
    public String getCode2() {
        return this.code2;
    }
    
    public void setCode2(String code2) {
        this.code2 = code2;
    }
    public Set getCountrylanguages() {
        return this.countrylanguages;
    }
    
    public void setCountrylanguages(Set countrylanguages) {
        this.countrylanguages = countrylanguages;
    }




}


