package model;
// Generated 21/09/2019 16:14:32 by Hibernate Tools 4.3.1



/**
 * Countrylanguage generated by hbm2java
 */
public class Countrylanguage  implements java.io.Serializable {


     private CountrylanguageId id;
     private Country country;
     private boolean isofficial;
     private float percentage;

    public Countrylanguage() {
    }

    public Countrylanguage(CountrylanguageId id, Country country, boolean isofficial, float percentage) {
       this.id = id;
       this.country = country;
       this.isofficial = isofficial;
       this.percentage = percentage;
    }
   
    public CountrylanguageId getId() {
        return this.id;
    }
    
    public void setId(CountrylanguageId id) {
        this.id = id;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public boolean isIsofficial() {
        return this.isofficial;
    }
    
    public void setIsofficial(boolean isofficial) {
        this.isofficial = isofficial;
    }
    public float getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(float percentage) {
        this.percentage = percentage;
    }




}


