package model;
// Generated 21/09/2019 16:14:32 by Hibernate Tools 4.3.1



/**
 * CountrylanguageId generated by hbm2java
 */
public class CountrylanguageId  implements java.io.Serializable {


     private String countrycode;
     private String language;

    public CountrylanguageId() {
    }

    public CountrylanguageId(String countrycode, String language) {
       this.countrycode = countrycode;
       this.language = language;
    }
   
    public String getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CountrylanguageId) ) return false;
		 CountrylanguageId castOther = ( CountrylanguageId ) other; 
         
		 return ( (this.getCountrycode()==castOther.getCountrycode()) || ( this.getCountrycode()!=null && castOther.getCountrycode()!=null && this.getCountrycode().equals(castOther.getCountrycode()) ) )
 && ( (this.getLanguage()==castOther.getLanguage()) || ( this.getLanguage()!=null && castOther.getLanguage()!=null && this.getLanguage().equals(castOther.getLanguage()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCountrycode() == null ? 0 : this.getCountrycode().hashCode() );
         result = 37 * result + ( getLanguage() == null ? 0 : this.getLanguage().hashCode() );
         return result;
   }   


}


